### PR TITLE
Add tryExclusiveLock, tryUpgradeLock, downgradeLock and prevent reader starvation with write barrier

### PR DESCRIPTION
**Pull request by oerdnj**
Hi,

thank you for all the code you publish!

I've been implementing C-RW-WP in C11 based on your code and here are few extra things I needed:

* ::tryExclusiveLock has been implemented
* Writer Barrier has been implemented (based on the paper) to prevent starving the readers
* ::tryUpgradeLock and ::downgradeLock has been implemented (I am just not sure about the naming)

The paper also talks about replacing the readersCounters with ingress and egress counters to remove the intra-node contention - I can also do that, but for our purposes the code works fine.

I can also submit the C11 code if you want - I would just need to clean it up a bit, because it's currently plugged in into BIND 9 code.

### CODE REVIEW

**Comment by pramalhe** [comment]
Hi Oerdnj,
The algorithm described in the "NUMA-aware reader-write lock" paper does indeed have the additions that you propose. However, IMO the addition of the braised flag twist the purpose of this rw-lock: provide write-preference. Not to mention it adds complexity without a clear benefit coming from it.
I don't want such modifications in DCLCRWlock. However, if you're still up for it, you can add a new class that follows the algorithm as you have implemented it (as is described in the paper), just name it something appropriate. I can suggest DCCRWWPOrig, but I'm fine with any naming you come up with.
Thank you so much for your hard work.
Pedro

**Comment by oerdnj** [comment]
Sure, then we can just cherry-pick the tryExclusiveLock and perhaps downgradeLock and tryUpgradeLock?

Or... I can try to convince you that the wBarrier is actually needed for practical applications.

In BIND 9, the current rwlock is used to lock our own rbtdb database (which is rbt twisted to be used as DNS tree, so it has its own quirks). The busy DNS server generally does lot of writes when the cache is cold and then the reads are more common, but the writes still take place (entries gets removed, new data gets into the cache...).[a]

The current isc rwlock implementation is quite old with adaptive spinning added on top - but the devil is in the detail. The isc_rwlock implements write_quota which makes one Reader to wake up for every n (4 by default) completed Writers.

At the same time, the clients expect a response within limited time interval.

It might be unique to our workload, but our non-synthetic benchmark shows a clear cut when the cache is filled and reads are more common and this hurts the application performance (also the Readers keep pilling up).

In the synthetic micro benchmark I wrote, I see no difference in performance for a version with and without the wBarrier.

I'll provide some numbers and graphs when I am not on mobile device.

a) as a side note, I have my eye on your left-right to be used instead of the rwlock for some uses in the data structure holding the DNS data.

**Comment by pramalhe** [comment]
Yes, a good starvation-free (fair) with high read-scalability is yet to be published. We have a couple of them but didn't have time to write the paper yet.
Sure, you can cherry pick tryExclusiveLock and downgradeLock and tryUpgradeLock, but to be clear, you can have everything just like you implemented, it's just a matter of using a different class name/file. I just don't want to change the algorithm that is currently being used in that class, but I'm ok (and welcome) adding new algorithms and variants!

**Comment by pramalhe** [comment]
Thanks for the upgrade (and downgrade)  :)

**Pull request merged**
